# Generated by Django 5.0.9 on 2024-10-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
