# Generated by Django 5.0.9 on 2024-10-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymDB', '0002_delete_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(to='GymDB.permissions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GymDB.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='gym_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='role',
            field=models.ManyToManyField(to='GymDB.permissions'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='gym_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GymDB.pass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_create_e_account',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_e_account',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_schedule',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_reset_pswds',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_view_schedule',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='role',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='account',
            field=models.CharField(choices=[('JA', 'Janitorial')], default='JA', max_length=2),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
